version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: wallet_server
    ports:
      - 8001:80
      - 4430:443
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
      - db
    networks:
      - wallet

  php:
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - wallet
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wallet_transactions
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8306:3306
    networks:
      - wallet



networks:
  wallet:
    driver: bridge
